### ISSUE TITLE
Random Profiles error

### ISSUE THREAD

**Issue by Greenfoot5** [Q-Sharp/BattleBot#5]
**Describe the bug**
Stops users from selecting a random profile

**To Reproduce**
1. Use `b!p`. Can be any profile
2. Click on the random profiles reaction (the record reaction)
3. Error should be displayed in chat.

**Expected behavior**
The embed is updated to a different, random profile.

**What platform are you using discord on?**
Android Canary. v11.1

**Error Message**
```
Ignoring exception in command profile:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/discord/ext/commands/core.py", line 83, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/greenfoot5/ftp/files/BattleBot-stable/cogs/profiles.py", line 153, in profile
    colour = player.colour,
AttributeError: 'dict' object has no attribute 'colour'
```

**Comment by Greenfoot5** [comment]
Clearly forgot to update this from class based system to json. Just a small edit needed.

**Comment by Greenfoot5** [comment]
Seems it's not the colour, I haven't changed any of the random profile settings to match with json. I'll try to bring this in with the options branch.

**Comment by Greenfoot5** [comment]
The base has been coded. I will just need to test and confirm it's all working correctly.
